import type { Project } from './types.js';

const H = 60 * 60 * 1000;
const D = 24 * H;

/**
 * The nine launch projects. All timestamps are computed relative to `now`
 * so live/upcoming windows are correct whenever the DB is (re)seeded.
 * All names, tickers, addresses and numbers are synthetic demo data.
 */
export function buildSeedProjects(now: Date = new Date()): Project[] {
  const t = now.getTime();
  const iso = (offsetMs: number) => new Date(t + offsetMs).toISOString();

  return [
    {
      slug: 'heliora',
      name: 'Heliora',
      ticker: 'HELIO',
      chain: 'SOL',
      sector: 'DePIN',
      status: 'live',
      description: 'Decentralized solar telemetry network turning rooftop arrays into yield-bearing infrastructure nodes.',
      about:
        'Heliora deploys plug-in telemetry units on residential and commercial solar arrays, streaming verified production data on-chain. Energy retailers and grid operators pay for the feed; node operators earn HELIO proportional to uptime and data quality. The network already meters 41 MW across 3 pilot markets.',
      highlights: [
        '41 MW metered across 1,900 live nodes in 3 pilot markets',
        'Signed data-supply agreements with two EU energy retailers',
        'Hardware margin-positive since Q1 — token incentives fund growth, not losses',
        'Audited by Halborn; oracle design reviewed by OtterSec',
      ],
      logo: { letter: 'H', from: '#FFB45C', to: '#FF6A3C' },
      contract: 'HeLi0raSo1arNetw0rkT0kenM1nt11111111111111111',
      socials: { website: 'https://heliora.network', x: 'https://x.com/heliora', discord: 'https://discord.gg/heliora', docs: 'https://docs.heliora.network' },
      tokenomics: [
        { label: 'Public Sale', pct: 12 },
        { label: 'Ecosystem & Rewards', pct: 30 },
        { label: 'Liquidity', pct: 18 },
        { label: 'Team', pct: 15 },
        { label: 'Treasury', pct: 15 },
        { label: 'Advisors', pct: 10 },
      ],
      vesting: { tgePct: 20, cliffMonths: 1, linearMonths: 6 },
      supply: 1_000_000_000,
      initMcap: 6_300_000,
      fdv: 42_000_000,
      listing: 'Raydium + 2 CEX · T+2 days',
      softCap: 250_000,
      hardCap: 850_000,
      price: 0.042,
      startAt: iso(-34 * H),
      endAt: iso(14 * H),
      raised: 611_400,
      participants: 4_213,
      audited: true,
      kycTeam: true,
    },
    {
      slug: 'voltaic',
      name: 'Voltaic',
      ticker: 'VOLT',
      chain: 'BASE',
      sector: 'Infra',
      status: 'live',
      description: 'Real-time settlement layer for EV charging networks, built as a Base-native payments rail.',
      about:
        'Voltaic lets charging networks settle roaming sessions between operators in seconds instead of weeks, with fees an order of magnitude below card rails. VOLT stakers underwrite settlement liquidity and earn a cut of every session cleared. 26 networks across 4 countries are in the integration pipeline.',
      highlights: [
        'Clearing live sessions with 3 charging networks since March',
        'Settlement volume growing 38% month-over-month',
        'Backed by two of the top EV-infrastructure venture funds',
      ],
      logo: { letter: 'V', from: '#59D0FF', to: '#3773F5' },
      contract: '0x7A3fE29b41c8D0aF6c2E845a9B17d3C4e8F9a012',
      socials: { website: 'https://voltaic.energy', x: 'https://x.com/voltaic', docs: 'https://docs.voltaic.energy' },
      tokenomics: [
        { label: 'Public Sale', pct: 15 },
        { label: 'Network Incentives', pct: 28 },
        { label: 'Liquidity', pct: 15 },
        { label: 'Team', pct: 18 },
        { label: 'Treasury', pct: 16 },
        { label: 'Strategic', pct: 8 },
      ],
      vesting: { tgePct: 25, cliffMonths: 0, linearMonths: 4 },
      supply: 250_000_000,
      initMcap: 4_800_000,
      fdv: 20_000_000,
      listing: 'Aerodrome · T+1 day',
      softCap: 200_000,
      hardCap: 600_000,
      price: 0.08,
      startAt: iso(-20 * H),
      endAt: iso(38 * H),
      raised: 342_800,
      participants: 2_871,
      audited: true,
      kycTeam: false,
    },
    {
      slug: 'nebulith',
      name: 'Nebulith',
      ticker: 'NEB',
      chain: 'ETH',
      sector: 'AI',
      status: 'live',
      description: 'Verifiable inference marketplace where model providers prove outputs with succinct attestations.',
      about:
        'Nebulith routes inference jobs to a network of GPU providers and attaches cryptographic attestations to every response, so consumers can verify which model actually ran. NEB is the work token: providers bond it for job priority, and verifiers earn it for spot-checking attestations.',
      highlights: [
        '2.1M attested inference jobs processed on testnet',
        '87 independent GPU providers onboarded',
        'Attestation scheme peer-reviewed and published at a top systems conference',
        'Audited by Trail of Bits',
      ],
      logo: { letter: 'N', from: '#C48AFF', to: '#7C6CFF' },
      contract: '0x94bD11eA30F27C55908c3F1a6dE0b4a892E5c731',
      socials: { website: 'https://nebulith.ai', x: 'https://x.com/nebulith', discord: 'https://discord.gg/nebulith', docs: 'https://docs.nebulith.ai' },
      tokenomics: [
        { label: 'Public Sale', pct: 10 },
        { label: 'Provider Incentives', pct: 32 },
        { label: 'Liquidity', pct: 12 },
        { label: 'Team', pct: 17 },
        { label: 'Foundation', pct: 21 },
        { label: 'Advisors', pct: 8 },
      ],
      vesting: { tgePct: 15, cliffMonths: 1, linearMonths: 8 },
      supply: 500_000_000,
      initMcap: 9_700_000,
      fdv: 75_000_000,
      listing: 'Uniswap + 1 CEX · T+3 days',
      softCap: 400_000,
      hardCap: 1_200_000,
      price: 0.15,
      startAt: iso(-60 * H),
      endAt: iso(6 * H),
      raised: 1_027_500,
      participants: 6_544,
      audited: true,
      kycTeam: true,
    },
    {
      slug: 'kitsune',
      name: 'Kitsune',
      ticker: 'KSN',
      chain: 'BNB',
      sector: 'GameFi',
      status: 'upcoming',
      description: 'Competitive extraction RPG where seasonal loot economies are settled entirely on-chain.',
      about:
        'Kitsune runs three-month seasons: players raid procedurally generated shrines, extract artifacts, and trade them on an on-chain bazaar that burns KSN on every sale. The studio shipped two profitable mobile titles before going on-chain and funds development from revenue, not emissions.',
      highlights: [
        '412K wishlists across launch platforms',
        'Closed beta retention: 41% day-30',
        'Season 0 artifact mint sold out in 11 minutes',
      ],
      logo: { letter: 'K', from: '#FF5C7A', to: '#FFB35C' },
      contract: null,
      socials: { website: 'https://kitsune.gg', x: 'https://x.com/kitsunegg', discord: 'https://discord.gg/kitsune' },
      tokenomics: [
        { label: 'Public Sale', pct: 14 },
        { label: 'Play & Season Rewards', pct: 30 },
        { label: 'Liquidity', pct: 16 },
        { label: 'Team', pct: 16 },
        { label: 'Treasury', pct: 14 },
        { label: 'Partners', pct: 10 },
      ],
      vesting: { tgePct: 25, cliffMonths: 0, linearMonths: 5 },
      supply: 5_000_000_000,
      initMcap: 7_100_000,
      fdv: 55_000_000,
      listing: 'PancakeSwap · T+1 day',
      softCap: 150_000,
      hardCap: 450_000,
      price: 0.011,
      startAt: iso(2 * D + 4 * H),
      endAt: iso(4 * D + 4 * H),
      raised: 0,
      participants: 0,
      audited: true,
      kycTeam: true,
    },
    {
      slug: 'auric',
      name: 'Auric',
      ticker: 'AUR',
      chain: 'SOL',
      sector: 'RWA',
      status: 'upcoming',
      description: 'Tokenized private-credit vaults sourcing short-duration invoice financing from vetted originators.',
      about:
        'Auric packages 30–90 day invoice-financing deals from three licensed originators into on-chain vaults with daily NAV. Historical originator default rate is under 0.4%, and every vault is over-collateralized by receivables insurance. AUR captures protocol fees and governs originator onboarding.',
      highlights: [
        '$18M in receivables financed off-chain by partner originators to date',
        'Receivables insured by an A-rated carrier',
        'Daily NAV published by an independent fund administrator',
      ],
      logo: { letter: 'A', from: '#EAD1A2', to: '#C9A366' },
      contract: null,
      socials: { website: 'https://auric.finance', x: 'https://x.com/auricfinance', docs: 'https://docs.auric.finance' },
      tokenomics: [
        { label: 'Public Sale', pct: 11 },
        { label: 'Ecosystem', pct: 24 },
        { label: 'Liquidity', pct: 14 },
        { label: 'Team', pct: 19 },
        { label: 'Treasury', pct: 22 },
        { label: 'Advisors', pct: 10 },
      ],
      vesting: { tgePct: 10, cliffMonths: 2, linearMonths: 10 },
      supply: 120_000_000,
      initMcap: 5_500_000,
      fdv: 42_000_000,
      listing: 'Orca + 1 CEX · T+4 days',
      softCap: 300_000,
      hardCap: 900_000,
      price: 0.35,
      startAt: iso(5 * D),
      endAt: iso(7 * D),
      raised: 0,
      participants: 0,
      audited: false,
      kycTeam: true,
    },
    {
      slug: 'strato',
      name: 'Strato',
      ticker: 'STRAT',
      chain: 'BASE',
      sector: 'DeFi',
      status: 'tba',
      description: 'Intent-based perps aggregator routing orders across venues for best execution with one margin account.',
      about:
        'Strato lets traders express an intent — size, direction, max slippage — and routes it across perp venues on Base for best all-in execution, settled against a single cross-venue margin account. STRAT stakers share routing fees and backstop the insurance fund.',
      highlights: [
        '$310M cumulative volume routed during invite-only alpha',
        'Median execution improvement of 4.1 bps vs. best single venue',
        'Insurance fund seeded with 8% of supply',
      ],
      logo: { letter: 'S', from: '#59E0C1', to: '#3773F5' },
      contract: null,
      socials: { website: 'https://strato.trade', x: 'https://x.com/stratotrade' },
      tokenomics: [
        { label: 'Public Sale', pct: 13 },
        { label: 'Trading Incentives', pct: 27 },
        { label: 'Liquidity', pct: 15 },
        { label: 'Team', pct: 18 },
        { label: 'Treasury', pct: 19 },
        { label: 'Strategic', pct: 8 },
      ],
      vesting: { tgePct: 20, cliffMonths: 1, linearMonths: 6 },
      supply: 400_000_000,
      initMcap: 5_200_000,
      fdv: 20_000_000,
      listing: 'TBA',
      softCap: 250_000,
      hardCap: 750_000,
      price: 0.05,
      startAt: null,
      endAt: null,
      raised: 0,
      participants: 0,
      audited: false,
      kycTeam: true,
    },
    {
      slug: 'pulsegrid',
      name: 'Pulsegrid',
      ticker: 'PULSE',
      chain: 'SOL',
      sector: 'DePIN',
      status: 'ended',
      description: 'Crowd-deployed vibration sensors that sell structural-health data on bridges and industrial sites.',
      about:
        'Pulsegrid nodes are palm-sized accelerometers bonded to bridges, cranes and factory floors. Municipalities and insurers subscribe to anomaly alerts; node hosts earn PULSE. The sale filled its hard cap and the token listed at 6.4× the sale price.',
      highlights: [
        'Hard cap filled — $500K raised from 8,112 participants',
        'Listed on KuCoin and Bybit at T+2',
        '11.2× all-time high vs. sale price',
      ],
      logo: { letter: 'P', from: '#3DD68C', to: '#59D0FF' },
      contract: 'Pu1seGr1dSens0rNetw0rkM1ntAddr3ss111111111111',
      socials: { website: 'https://pulsegrid.io', x: 'https://x.com/pulsegrid' },
      tokenomics: [
        { label: 'Public Sale', pct: 12 },
        { label: 'Node Rewards', pct: 34 },
        { label: 'Liquidity', pct: 16 },
        { label: 'Team', pct: 15 },
        { label: 'Treasury', pct: 15 },
        { label: 'Advisors', pct: 8 },
      ],
      vesting: { tgePct: 20, cliffMonths: 1, linearMonths: 6 },
      supply: 2_000_000_000,
      initMcap: 4_600_000,
      fdv: 40_000_000,
      listing: 'Listed · KuCoin, Bybit',
      softCap: 200_000,
      hardCap: 500_000,
      price: 0.02,
      startAt: iso(-45 * D),
      endAt: iso(-42 * D),
      raised: 500_000,
      participants: 8_112,
      audited: true,
      kycTeam: true,
      roi: 6.4,
      ath: 11.2,
      cex: ['KuCoin', 'Bybit'],
    },
    {
      slug: 'bastion',
      name: 'Bastion',
      ticker: 'BSTN',
      chain: 'ETH',
      sector: 'Security',
      status: 'ended',
      description: 'On-chain firewall that screens transactions against exploit signatures before they hit your contracts.',
      about:
        'Bastion sits between users and protocols as a policy layer: transactions matching known exploit patterns are challenged or blocked before execution. Nine protocols with $290M combined TVL run Bastion in production. BSTN gates policy updates and pays screeners.',
      highlights: [
        '$743K raised from 5,205 participants',
        '9 protocols protected in production',
        'Listed on Gate and MEXC at T+3',
      ],
      logo: { letter: 'B', from: '#98A2FF', to: '#627EEA' },
      contract: '0xB0571047F1c8E2a9D34bC65e8F0a1d2B3c4D5E6F',
      socials: { website: 'https://bastion.security', x: 'https://x.com/bastionsec', docs: 'https://docs.bastion.security' },
      tokenomics: [
        { label: 'Public Sale', pct: 10 },
        { label: 'Screener Rewards', pct: 26 },
        { label: 'Liquidity', pct: 14 },
        { label: 'Team', pct: 20 },
        { label: 'Treasury', pct: 20 },
        { label: 'Strategic', pct: 10 },
      ],
      vesting: { tgePct: 15, cliffMonths: 1, linearMonths: 9 },
      supply: 300_000_000,
      initMcap: 6_100_000,
      fdv: 36_000_000,
      listing: 'Listed · Gate, MEXC',
      softCap: 300_000,
      hardCap: 800_000,
      price: 0.12,
      startAt: iso(-30 * D),
      endAt: iso(-27 * D),
      raised: 743_000,
      participants: 5_205,
      audited: true,
      kycTeam: true,
      roi: 3.1,
      ath: 5.8,
      cex: ['Gate', 'MEXC'],
    },
    {
      slug: 'lumenreach',
      name: 'Lumenreach',
      ticker: 'LUM',
      chain: 'BNB',
      sector: 'SocialFi',
      status: 'ended',
      description: 'Creator subscription rails where fans hold revocable access keys and creators keep 97% of revenue.',
      about:
        'Lumenreach replaces platform lock-in with portable subscriber keys: creators publish anywhere, fans subscribe once, and revenue splits settle on-chain every hour. 3,400 creators migrated during the beta. LUM is burned on every settlement cycle.',
      highlights: [
        'Hard cap filled — $350K from 9,450 participants',
        '3,400 creators onboarded in beta',
        'Listed on Bitget at T+2',
      ],
      logo: { letter: 'L', from: '#F0B90B', to: '#FF7A3C' },
      contract: '0x1D2fE45c9A238b0aD67F91E2C84b5a3D0e6F7A8B',
      socials: { website: 'https://lumenreach.social', x: 'https://x.com/lumenreach' },
      tokenomics: [
        { label: 'Public Sale', pct: 16 },
        { label: 'Creator Incentives', pct: 30 },
        { label: 'Liquidity', pct: 18 },
        { label: 'Team', pct: 14 },
        { label: 'Treasury', pct: 14 },
        { label: 'Partners', pct: 8 },
      ],
      vesting: { tgePct: 30, cliffMonths: 0, linearMonths: 4 },
      supply: 10_000_000_000,
      initMcap: 3_900_000,
      fdv: 40_000_000,
      listing: 'Listed · Bitget',
      softCap: 150_000,
      hardCap: 350_000,
      price: 0.004,
      startAt: iso(-18 * D),
      endAt: iso(-15 * D),
      raised: 350_000,
      participants: 9_450,
      audited: true,
      kycTeam: false,
      roi: 1.9,
      ath: 4.2,
      cex: ['Bitget'],
    },
  ];
}
